---
plugins:
  # https://github.com/jest-community/eslint-plugin-jest
  - jest

env:
  node: true
  es2017: true

extends:
  - "airbnb-base"
  - "plugin:jest/recommended"

parserOptions:
  ecmaVersion: 10
  sourceType: module

rules:
  no-console: 0
  import/extensions: 0
