version: "3"

networks:
  db:
    driver: bridge

services:
  db:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_USER: reporter
      POSTGRES_PASSWORD: reporter
      POSTGRES_DB: lessons_report
    volumes:
      - .docker/db/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    ports:
      - "5432:5432"
    expose:
      - 5432
    restart: always
    networks:
      - db

  tests:
    build:
      context: .
      dockerfile: .docker/tests/Dockerfile
    environment:
      DB_HOST: db
      DB_USER: reporter
      DB_PASSWORD: reporter
      DB_DATABASE: lessons_report
    depends_on:
      - db
    links:
      - db
    networks:
      - db
